######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 29 15:58:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += matrix_character.h
SOURCES += main.cpp matrix_character.cpp
