######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 29 15:58:41 2016
######################################################################

TEMPLATE = app
TARGET = matrix

#include dir
DEPENDPATH += ./src
INCLUDEPATH += src
INCLUDEPATH += ./

HEADERS += src/matrix_character.h
SOURCES += src/main.cpp src/matrix_character.cpp
